[package]
name = "etle"
version = "0.1.0"
edition = "2024"

[lib]
name = "etle"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.102"
bincode = { version = "2.0.1", features = ["serde"] }
blake3 = "1.8.5"
chacha20poly1305 = "0.10.1"
clap = { version = "4.6.1", features = ["derive"], optional = true }
get_if_addrs = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "io-util",
    "time",
    "sync",
] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
x25519-dalek = "2.0.1"
relm4 = { version = "0.11", optional = true }
rfd = { version = "0.17", optional = true }

[features]
default = ["cli"]
cli = ["dep:clap"]
gui-relm4 = ["dep:relm4", "dep:rfd"]

[[bin]]
name = "etle-cli"
path = "src/bin/etle-cli.rs"
required-features = ["cli"]

[[bin]]
name = "etle-gui"
path = "src/bin/etle-gui.rs"
required-features = ["gui-relm4"]

[[bin]]
name = "etled"
path = "src/bin/etled.rs"
required-features = ["cli"]

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
